### PR TITLE
add fallbacks for when subtitle name is empty

### PR DESCRIPTION
**Pull request by tomasz-rekawek**
When `track.name` was empty it was adding serveral subtitles with autogenerated names like VJS_23134

### CODE REVIEW

**Comment by zemlanin** [comment]
Is this PR (still) necessary if/when stream provider responds with correctly id'd/named subtitles?

**Comment by tomasz-rekawek** [comment]
> Is this PR (still) necessary if/when stream provider responds with correctly id'd/named subtitles?

When it responds correctly it is redundant.

**Comment by zemlanin** [comment]
Do you want to merge this before contacting backend team?

**Review by zemlanin — APPROVED** [review]

**Comment by tomasz-rekawek** [comment]
> Do you want to merge this before contacting backend team?

I couldn't replicate the issue since last friday

**Pull request merged**
